export const PsiAbilityNames = [
  [
    'Psycho-Reflective Screen',
    'Neuro-Reflex Dampening',
    'Kinetic Redirection',
    'Psychogenic Agility',
    'Psychogenic Cyber Affinity',
    'Projected Cryokinesis',
    'Remote Electron Tampering',
  ],
  [
    'Anti-Entropic Field',
    'Adrenaline Overproduction',
    'Neural Decontamination',
    'Cerebro-Stimulated Regeneration',
    'Psychogenic Strength',
    'Recursive Psionic Amplification',
    'Localized Pyrokinesis',
  ],
  [
    'Molecular Duplication',
    'Electron Cascade',
    'Energy Reflection',
    'Neural Toxin-Blocker',
    'Enhanced Motion Sensitivity',
    'Projected Pyrokinesis',
    'Psionic Hypnogenesis',
  ],
  [
    'Photonic Redirection',
    'Remote Pattern Detection',
    'Electron Suppression',
    'Psychogenic Endurance',
    'Molecular Transmutation',
    'Remote Circuitry Manipulation',
    'Cerebro-Energetic Extension',
  ],
  [
    'Advanced Cerebro-Stimulated Regeneration',
    'Soma Transference',
    'Instantaneous Quantum Relocation',
    'Imposed Neural Restructuring',
    'Metacreative Barrier',
    'External Psionic Detonation',
    'Psycho-Reflective Aura',
  ],
];
